version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm start
    secrets:
      - mongo_uri
    environment:
      NODE_ENV: production
secrets:
  mongo_uri:
    external: true

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.frontend
    ports:
      - "80:80"
    stdin_open: true
    tty: true
